mpkg: add upgrade function
This function allows to upgrade given outdated packages (or all outdated
packages if no package is specified).

Package dependencies are not upgraded.

diff --git a/bin/mpkg b/bin/mpkg
--- a/bin/mpkg
+++ b/bin/mpkg
@@ -485,11 +485,39 @@ pkg_install() {
 		return 1
 	fi
 
+	# Upgrading package
+	if [ -d "$ROOT$PREFIX/info/$pkg/" ]; then
+		# Removing orphan dependencies
+		for dep in "$ROOT$PREFIX/info/$pkg/needs/"*; do
+			[ -L "$dep" ] || break
+
+			dep="${dep##*/}"
+			if [ -L "$tmpdir$PREFIX/info/$pkg/needs/$dep" ]; then
+				rm "$ROOT$PREFIX/info/$pkg/needs/$dep"
+				continue
+			fi
+
+			rm -f "$ROOT$PREFIX/info/$dep/required-by/$pkg"
+			if pkg_is_user_installed "$dep"; then
+				debug "Do not auto-remove user-installed package $dep! Keep going..."
+				continue
+			fi
+
+			if ! pkg_remove "$dep"; then
+				warning "Failed to remove package $dep! Keep going..."
+			fi
+
+			rm -f "$ROOT$PREFIX/info/$pkg/needs/$dep"
+		done
+
+		rmdir "$ROOT$PREFIX/info/$pkg/needs/"
+	fi
+
 	# Extract whole archive
 	debug "$pkg: Unarchiving package data..."
 	pkg_extract_data "$cachedir/$file" "${ROOT:-/}"
-	install -d "$ROOT$PREFIX/info/"
-	mv "$tmpdir$PREFIX/info/$pkg" "$ROOT$PREFIX/info/"
+	install -d "$ROOT$PREFIX/info/$pkg"
+	mv "$tmpdir$PREFIX/info/$pkg/"* "$ROOT$PREFIX/info/$pkg"
 	rm "$cachedir/$file"*
 
 	# Run postinst script if exists,
@@ -774,6 +802,28 @@ do_configure() {
 	done
 }
 
+do_upgrade() {
+	for pkg in $*; do
+		abort=false
+		if ! pkg_status "$pkg" >/dev/null; then
+			verbose "$pkg: Package not installed!"
+			continue
+		fi
+
+		if ! ver=$(pkg_is_outdated "$pkg"); then
+			verbose "$pkg: Package is up-to-date!"
+			continue
+		fi
+
+		debug "Upgrading package $pkg to $ver..."
+		requiredby=
+		if ! pkg_install "$pkg" "$ver"; then
+			die "Failed to upgrade $pkg!"
+		fi
+		debug "Package $pkg upgraded to $ver!"
+	done
+}
+
 usage() {
 	cat <<EOF
 Usage: ${0##*/} [OPTIONS] update
@@ -783,7 +833,7 @@ Usage: ${0##*/} [OPTIONS] update
        ${0##*/} [OPTIONS] status PACKAGE...
        ${0##*/} [OPTIONS] lock|unlock PACKAGE...
        ${0##*/} [OPTIONS] fetch PACKAGE...
-       ${0##*/} [OPTIONS] install|remove PACKAGE[_VERSION]...
+       ${0##*/} [OPTIONS] install|remove|upgrade PACKAGE[_VERSION]...
        ${0##*/} [OPTIONS] configure [PACKAGE...]
        ${0##*/} [OPTIONS] log
 
@@ -832,13 +882,13 @@ parse_arguments() {
 			echo $VERSION
 			exit 0
 		elif [ -z "$func" ]; then
-			if echo "$func" | grep -qE "update|list|list-installed|list-outdated|status|lock|unlock|fetch|install|remove|configure|log"; then
+			if echo "$func" | grep -qE "update|list|list-installed|list-outdated|status|lock|unlock|fetch|install|remove|upgrade|configure|log"; then
 				usage >&2
 				echo  >&2
 				die "$1: Unknown function!"
 			fi
 			func="$1"
-		elif echo "$func" | grep -qE "lock|unlock|fetch|install|remove"; then
+		elif echo "$func" | grep -qE "lock|unlock|fetch|install|remove|upgrade"; then
 			args="$args $1"
 		elif [ -z "$args" ]; then
 			args="$args $1"
@@ -937,6 +987,19 @@ remove)
 	fi
 
 	do_remove $args
+	;;
+upgrade)
+	if [ -z "$args" ]; then
+		usage >&2
+		echo  >&2
+		die "Too few arguments!"
+	fi
+
+	if $UPDATE; then
+		do_update
+	fi
+
+	do_upgrade $args
 	;;
 configure)
 	if [ -z "$args" ]; then
