mpkg: add the configure function.
This function allows to re-run the postinst script to re-configure any
packages installed but left unconfigured.

Without arguments (ie. package list), mpkg re-configures all unconfigured
packages. Otherwise, it re-configures all packages given into parameters.

Usage: ...
       mpkg [OPTIONS] configure [PACKAGE...]
...

Signed-off-by: Gaël PORTAY <gael.portay@gmail.com>

diff --git a/bin/mpkg b/bin/mpkg
--- a/bin/mpkg
+++ b/bin/mpkg
@@ -691,6 +691,27 @@ do_remove() {
 	done
 }
 
+do_configure() {
+	for pkg in $*; do
+		if ! pkg_status "$pkg" >/dev/null; then
+			echo "$pkg: Package not installed!"
+			continue
+		fi
+
+		if pkg_is_configured "$pkg" >/dev/null; then
+			echo "$pkg: Package is already configured!"
+			continue
+		fi
+
+		echo "Configuring package $pkg..."
+		if ! pkg_configure "$pkg"; then
+			die "Failed to configure $pkg!"
+		fi
+		pkg_set_configured "$pkg"
+		echo "Package $pkg configured!"
+	done
+}
+
 usage() {
 	cat <<EOF
 Usage: ${0##*/} [OPTIONS] update
@@ -701,6 +722,7 @@ Usage: ${0##*/} [OPTIONS] update
        ${0##*/} [OPTIONS] lock|unlock PACKAGE...
        ${0##*/} [OPTIONS] fetch PACKAGE...
        ${0##*/} [OPTIONS] install|remove PACKAGE[_VERSION]...
+       ${0##*/} [OPTIONS] configure [PACKAGE...]
        ${0##*/} [OPTIONS] log
 
 Options:
@@ -748,7 +770,7 @@ parse_arguments() {
 			echo $VERSION
 			exit 0
 		elif [ -z "$func" ]; then
-			if echo "$func" | grep -qE "update|list|list-installed|list-outdated|status|lock|unlock|fetch|install|remove|log"; then
+			if echo "$func" | grep -qE "update|list|list-installed|list-outdated|status|lock|unlock|fetch|install|remove|configure|log"; then
 				usage >&2
 				echo  >&2
 				die "$1: Unknown function!"
@@ -848,6 +870,13 @@ remove)
 	fi
 
 	do_remove $args
+	;;
+configure)
+	if [ -z "$args" ]; then
+		args="$(find $ROOT$PREFIX/info/ -name '.configure' | sed 's,.*/\(.*\)/.configure,\1,')"
+	fi
+
+	do_configure $args
 	;;
 log)
 	if $CLEAR; then
