mpkg: introduce and use error function
The error() function prints message in red to stderr.

diff --git a/bin/mpkg b/bin/mpkg
--- a/bin/mpkg
+++ b/bin/mpkg
@@ -11,6 +11,10 @@ PREFIX=/var/lib/mpkg
 VERSION=0.2.0
 UPDATE=false
 
+error() {
+	echo -e "\e[31;1;4mERROR:\e[0m \e[31m$*\e[0m" >&2
+}
+
 debug() {
 	${DEBUG:-true} "\e[33;1;4mDEBUG:\e[0m \e[33m$*\e[0m" >&2
 }
@@ -505,10 +509,10 @@ pkg_remove() {
 	if ! pkg_status "$pkg" >/dev/null; then
 		return
 	elif pkg_is_locked "$pkg"; then
-		verbose "Error: $pkg: Cannot remove package! It is locked."
+		error "$pkg: Cannot remove package! It is locked."
 		return 1
 	elif required_by=$(pkg_get_required_by "$pkg"); then
-		verbose "Error: $pkg: Cannot remove package! It is required by: $required_by."
+		error "$pkg: Cannot remove package! It is required by: $required_by."
 		return 1
 	fi
 
