mpkg: run preinst script before installing deps
In order to halt installation as soon a possible and because it is a
pre-installation script.

diff --git a/bin/mpkg b/bin/mpkg
--- a/bin/mpkg
+++ b/bin/mpkg
@@ -434,6 +434,12 @@ pkg_install() {
 	install -d "$tmpdir$PREFIX/info/$pkg/needs/"
 	install -d "$tmpdir$PREFIX/info/$pkg/required-by/"
 
+	# Run preinst script if exists
+	if ! pkg_run_script "$tmpdir$PREFIX/info/$pkg" preinst install; then
+		error "$pkg: Failed to run preinst!"
+		return 1
+	fi
+
 	# Install missing dependencies
 	local depends
 	local dep
@@ -476,12 +482,6 @@ pkg_install() {
 			rm -f "$tmpdir$PREFIX/info/$pkg/needs/$rmdep"
 		done
 
-		return 1
-	fi
-
-	# Run preinst script if exists
-	if ! pkg_run_script "$tmpdir$PREFIX/info/$pkg" preinst install; then
-		error "$pkg: Failed to run preinst!"
 		return 1
 	fi
 
