mpkg: run prerm script before removing deps
In order to halt removeal as soon a possible and because it is a
pre-removal script.

It is the remove equivalent for:

	d8a375b mpkg: run preinst script before installing deps

diff --git a/bin/mpkg b/bin/mpkg
--- a/bin/mpkg
+++ b/bin/mpkg
@@ -364,6 +364,12 @@ pkg_remove() {
 		return 1
 	fi
 
+	# Run prerm script if exists
+	if ! pkg_run_script "$ROOT$PREFIX/info/$pkg" prerm remove; then
+		echo "$pkg: Failed to run prerm!" >&2
+		return 1
+	fi
+
 	echo "$pkg: Removing package${autoremovedby:+ auto-removed by$autoremovedby}..."
 
 	local depends
@@ -387,12 +393,6 @@ pkg_remove() {
 		fi
 		autoremovedby="${autoremovedby% *}"
 	done
-
-	# Run prerm script if exists
-	if ! pkg_run_script "$ROOT$PREFIX/info/$pkg" prerm remove; then
-		echo "$pkg: Failed to run prerm!" >&2
-		return 1
-	fi
 
 	# Extract whole archive
 	echo "$pkg: Removing package data..."
