mpkg: do_update: print warning for invalid lines in feeds.conf.
Each line must contains 2 properties, serparted by a single space.

Example:
local file:///var/www/tgz/Index

Run:
$ cat <<EOF >/etc/mpkg/feeds.conf
local file:///var/www/tgz/Index
EOF

Signed-off-by: Gaël PORTAY <gael.portay@gmail.com>

diff --git a/bin/mpkg b/bin/mpkg
--- a/bin/mpkg
+++ b/bin/mpkg
@@ -335,6 +335,11 @@ pkg_remove() {
 do_update() {
 	install -d "$ROOT$PREFIX/lists/"
 	sed -e '/^#/d' "$ROOT/etc/mpkg/feeds.conf" 2>/dev/null | while read name url; do
+		if [ -z "$url" ]; then
+			echo "Warning: Invalid line \"$name\"!" >&2
+			continue
+		fi
+
 		echo -n "Updating feed $name at $url... "
 		fetch "$url" "$ROOT$PREFIX/lists/$name"
 		md5sum "$ROOT$PREFIX/lists/$name" | cut -d' ' -f1
